services:
  nuggit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set the API URL for frontend - update this for your production domain
        VITE_API_BASE_URL: "https://your-production-domain.com/api"
    ports:
      - "8001:8001"  # Backend port
      - "5173:5173"  # Frontend port
    volumes:
      - ./nuggit/.env:/app/nuggit/.env:ro  # Mount .env file
      - ./nuggit/nuggit.db:/app/nuggit/nuggit.db  # Mount database file from correct source location
      - ./nuggit:/app/nuggit  # Mount source code for development
      - ./nuggit/frontend:/app/frontend  # Mount frontend source code
      - /app/frontend/node_modules  # Exclude node_modules from volume mount
    restart: unless-stopped
    env_file:
      - ./nuggit/.env  # All environment variables are read from .env file
